### ISSUE TITLE
Report errors caused by blockchain client desynchronization to the Golem client with HTTP 502

### ISSUE THREAD

**Issue by kbeker** [golemfactory/concent#1060] opened 2019-01-10 13:25 UTC
[GolemSmartContractInterface](https://github.com/golemfactory/golem-smart-contracts-interface) has [is_synchronized()](https://github.com/golemfactory/golem-smart-contracts-interface/blob/3ded8bc46937ce97218ca03f14f1d38c0f7a7fd7/golem_sci/client.py#L268) method which return `True` or `False`.

There should be added validation which would tell if SCI instance is synchronized or not. If SCI instance is not synchronized it should return `ServiceRefused` to client. It may be necessary to add new `REASON` to `GolemMessages`

Lack of this validation caused #960.

**Comment by cameel** [comment] 2019-01-10 13:52
This is not really a validation. Validations are for input. Validation implies that the client can make sure that his data is valid and successfully pass all the checks. That's not the case here. Desynchronized blockchain client is a failure of an internal (or external) service.

Don't check it with `is_synchronized()`. Even if you check it, the client may lose synchronization just after the check and your operation will fail anyway. You should just catch the exceptions (please make sure there's a specific exception type for this) caused by desynchronization. When you catch one, Concent should report an error to the client.

I initially suggested `ServiceRefused` but now I think it should be HTTP 502.

**Comment by PaweuB** [comment] 2019-01-11 10:44
Pivotal:
https://www.pivotaltracker.com/story/show/163144000

**Comment by cameel** [comment] 2019-01-17 18:20
@dybi I was told that SCI raises an exception in case of desynchronization. I haven't checked this myself. @kbeker @bartoszbetka @Jakub89 Does it? If it does not, we need to know what happens. Does the client accept the transaction? Does it fail silently?

@kbeker 
> Lack of this validation caused #960.

Is this the right issue?

**Comment by rwrzesien** [comment] 2019-01-21 00:54
Isn't it https://talkback.golem.network/sentry/concent/issues/37070/ ? If yes, I think it would be best to catch this exception directly in a place where SCI method is called (`core.payments.backends.sci_backend`), check the code, raise our custom exception, and handle it in decorators.

**Comment by cameel** [comment] 2019-01-21 11:39
I don't think that's it. We keep track of `nonce` internally - it does not matter whether the client is out of sync or not.

**Comment by cameel** [comment] 2019-01-21 15:03
>  `There are currently no blocks after 1547651804`

This is not coming from geth. It's raised by `get_first_block_after()` helper from SCI:

``` python
        if res.timestamp <= timestamp:
            raise ValueError(
                'There are currently no blocks after {}'.format(timestamp))
```

This happens when you call `get_first_block_after()` giving it a timestamp that's younger than anything than SCI can see on the blockchain.

We're giving it the timestamp of the acceptance sent by the provider. In theory it could be slightly in the future so we don't want an exception in this case. We want to simply have a value that indicates that there are no blocks after this timestamp (`None`)? Or a custom exception type so that we can safely catch it and ignore it. At most we might want to log it.

It can also happen if the client is not synchronized. If it's way out of sync, we might want to interrupt UC5 to avoid working with old data. But if it's only slightly out of sync, we don't want to interrupt the operation.

The question is: how to discern these two situations?

**Comment by cameel** [comment] 2019-01-21 15:12
> `{'code': -32000, 'message': 'missing trie node 2c7d74c7796bf936ab26db6b2846c835b05d076631483a2a2033d088d88e95a5 (path )'}`

This happens when we're checking GNT balance of a deposit, not when we're making a payment. It comes directly from Geth, SCI only passes it through. Big desynchronization may indeed be a problem. It would give us the wrong balance.

Overall looks like none of these exceptions happens when we're submitting a transaction to the client. So we can assume that a desynchronized client will accept it just fine. @bartoszbetka I think we need to remove the readiness probe if that's the case.

For now, when these exceptions do happen, HTTP 502 is the right response so we should catch them and reraise as a custom exception.

But as indicated above, the result is that sometimes a small desynchronization results in an error. We have to find a way to relax these checks in a safe way. For example a desynchronization of less than 6 blocks is completely safe because those blocks are not yet  confirmed anyway.

**Comment by rwrzesien** [comment] 2019-01-21 16:15
Closing as there is no real problem here, and a new issue is created to fix small desynchronizations problem https://github.com/golemfactory/concent/issues/1077.

**Closed by rwrzesien** 2019-01-21 16:15 UTC
Labels: bankster, bug

**Comment by cameel** [comment] 2019-01-21 17:18
Just to make things clear: these exceptions do happen due to client desynchronization and the fact that they result in HTTP 500 (which indicates a random failure in Concent's Python code, possibly a bug) rather than HTTP 502 (which indicates a failure of another service it depends on) is a problem. But the new issue covers this and more.

We have decided that since `is_synchronized()` does not report desynchronization immediately and for 10 seconds assumes that it's still fine, using it is (at least for now) the best and easiest way to make Concent less sensitive to a very brief loss of synchronization. It's better to solve this in a new issue with a clear description.
