### ISSUE TITLE
Soft shutdown for Concent service

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#152] opened 2018-02-26 14:08 UTC
@cameel Adding this to discuss implementation details.

I would see it this way:
1. Somehow shutdown is triggered (how ? this is the part I would like to ask you).
2. We set the flag on Concent that is it in shutdown mode (django-live-settings might be good for this).
3. Flag is checked in `send`, no new request is accepted, error message is returned (what code could it be ?)
4. In `receive` and `receive-out-of-band`, according to https://github.com/golemfactory/concent/issues/139 we will be checking all pending messages for timeout for current client. In that place, if the flag is raised, we can also check if there are any messages left globally, for all clients. If no, then perform a shutdown (does it mean stop django server ? If yes, how we want to do it ? By stopping it via supervisorctl ?). Also, should we treat timeouted messages, which can be still received by clients, as those which hold server from shutting down ?

The problem with this solution I see is that server instance might be never stopped, if there will be unreceived messages by client, or clients will stop sending requests to server when it is in shutdown mode. We might also introduce some graceful shutdown time as setting, and check it in point 4.

**Comment by cameel** [comment] 2018-02-26 19:44
I'm quoting your whole description because we'll need to replace it with the actual task description and my answer may not make sense without context:

> @cameel Adding this to discuss implementation details.
>
> I would see it this way:
> 1. Somehow shutdown is triggered (how ? this is the part I would like to ask you).
> 2. We set the flag on Concent that is it in shutdown mode (django-live-settings might be good for this).
> 3. Flag is checked in `send`, no new request is accepted, error message is returned (what code could it be ?)
> 4. In `receive` and `receive-out-of-band`, according to https://github.com/golemfactory/concent/issues/139 we will be checking all pending messages for timeout for current client. In that place, if the flag is raised, we can also check if there are any messages left globally, for all clients. If no, then perform a shutdown (does it mean stop django server ? If yes, how we want to do it ? By stopping it via supervisorctl ?). Also, should we treat timeouted messages, which can be still received by clients, as those which hold server from shutting down ?
>
> The problem with this solution I see is that server instance might be never stopped, if there will be unreceived messages by client, or clients will stop sending requests to server when it is in shutdown mode. We might also introduce some graceful shutdown time as setting, and check it in point 4.

For now I see the whole feature as a very passive thing. Flip a setting and add something that lets the admin see what's left in the system. It's the admin that flips it, monitors remaining tasks and makes a decision whether to pull the plug.

#### The switch
The switch is going to be just a boolean setting. We change the setting by editing config maps in concent-deployment, stopping containers running Concent API one by one and starting new ones. Concent API containers are stateless (the whole state is in the database which keeps running) so stopping them is not a big deal. It's a standard rolling update on Kubernetes. You don't have to worry about this. Just ensure that the application works as designed with each value. You can assume that the value won't change at runtime (e.g. in the middle of a request). But you can have containers with different values connected to the same database for a short period of time. They don't communicate with each other directly so it's not a problem.

#### `send/` behavior
When the switch is active, `send/`:
- won't accept anything that would cause a transition to an active state (from a yellow state to a blue one on the diagram in #137),
- won't accept payment requests,
- will accept messages that cause a transition to a passive state,
- will respond with HTTP errors and/or `ServiceRefused` to invalid requests,
- will process timeouts, including all side effects like checking if files have been uploaded

#### `receive/` and `receive-out-of-band/` behavior
The receive queue is just a passive mechanism that hands out messages and should keep working as before. Just as with send, timeouts should be processed normally because they can only lead to a transition to a passive state which is what we want.

Messages don't need to be all delivered for us to consider the system stopped. The only thing that matters is Concent's internal state.

Stop should not cause any messages to be removed or marked as delivered when they actually weren't. We may want to just turn the system back on and continue as if nothing happended. Or we may clear the database in which case they won't matter.

#### Gatekeeper behavior
Gatekeeper should have this setting too. When the switch is active, it should reject all tokens.
- Best if we respond with the same error `send/` does but if it's too hard, HTTP 401 is acceptable too for now.
- It should still respond to HEAD requests with full information so that Concent API can check if a file transfer has finished.
    - This would make the response to a HEAD request different than a response to a GET request which might be a bad idea. We have to check if HTTP spec says anything about a situation like this.
    - Maybe it would be better to reject requests (both HEAD and GET) from everyone but Concent API. We know if it's Concent API by looking at the `Concent-Client-Public-Key` header (or the auth message after we have full auth (#138)).

#### The error response
I think that it would be best to respond with `ServiceRefused` but we would need a special reason added in golem-messages.

Alternatively HTTP 503 SERVICE UNAVAILABLE is also acceptable. Please make sure that it's a JSON response and not a HTML page.

#### Shutdown
The server should never terminate on its own. This would be intepreted as a crash by Kubernetes and the container would be restarted (unless we configure the pod in a special way but let's not get into details here).

What we want instead is a way for the admin to see that it's safe to stop. He'll then decide if he wants to stop it and do it or not. You should be prepared that he'll change his mind and just flip the setting back and restart the containers.

#### How to know if containers have stopped
The admin will log into the admin panel and look at the subtask table. So we need the subtask list there. We also need a filter that shows only tasks in active states.

A list showing the state of the receive queue would also be useful. With the ability to show only undelivered messages.

If possible, configure the admin panel to be in read-only mode, so that it's not possible to change any database records. But if that's not possible or requires extra work, just use it as is. The main point here is that we want it to be as vanilla as possible. Don't build your own admin panel pages. Use what Django gives you and just slightly adjust it to our needs. It does not need to be user-friendly or have (too many) safeguards.

An e-mail notification when the last active subtask switches to a passive state would also be useful. But just once so that the admin is not flooded with e-mails when the system stops.

**Comment by rwrzesien** [comment] 2018-03-20 15:18
@cameel 
> The switch is going to be just a boolean setting. We change the setting by editing config maps in concent-deployment, stopping containers running Concent API one by one and starting new ones. Concent API containers are stateless (the whole state is in the database which keeps running) so stopping them is not a big deal. It's a standard rolling update on Kubernetes. You don't have to worry about this. Just ensure that the application works as designed with each value. You can assume that the value won't change at runtime (e.g. in the middle of a request). But you can have containers with different values connected to the same database for a short period of time. They don't communicate with each other directly so it's not a problem.

This is the part that is not clear to me. Should the switch be a setting, like django settings, which will be changed by changing paths to settings (I don't think that would work in runtime) or a setting in database ?

**Comment by rwrzesien** [comment] 2018-03-21 14:22
@cameel After today's discussion.

Ad 1) We will use django-live-settings and store shutdown flag in database.
Ad 2) Currently it doesn't matter, I will add fields which I feel should be visible to admin. After all it is very easy to hide them.
Ad 3) We use pure django send_email.

**Comment by cameel** [comment] 2018-03-26 16:22
Please do not close this when #191. We have identified a serious problem in the solution with live settings. Stuff on the storage cluster does not use the same database. There's also no way to set the flag. I need to think about a solution.

**Comment by cameel** [comment] 2018-04-26 16:01
After thinking about it I came to a conclusion that we don't need soft shutdown on the storage cluster. As long as we know that all subtasks on the control cluster are in passive states we can safely shut down both (control cluster should be stopped first). The only problem is with downloads but we had that problem before too.

Let's consider all possible cases:
- **Upload**: uploads are possible only in active states: `FORCING RESULT TRANSFER` and `VERIFICATION FILE TRANSFER`. If we're in a passive state the upload must have ended. In the future we'll have strict limits on upload times but even without them stopping an upload that was started in one of these states and is still in progress is actually a good thing.
- **Downloads**: this is the only one that can happen in a passive state. The only bad thing that can happen here is that requestor won't be able to finish his download. But that would still be a problem even if we had soft shutdown for the storage cluster because requestor can come for the file at any time in his time window and he still needs to be able to get the token from the control cluster during that time. The only way to protect against it is to make sure that subtasks in `RESULT UPLOADED` state are all past the guaranteed download deadline (`TaskToCompute.deadline` + SVT).
- **Verification**: no verification is supposed to be running when we're in a passive state. If it's still running for some reason while the subtask has timed out on the control cluster, stopping it is a good thing. The result will not be taken into account by the control cluster anyway.
- **Control cluster checking if a file has been uploaded**: this obviously won't happen when we shut down the control cluster.
- **Control cluster accessing the task queue**: same as above.

So, things to change in the implementation:
- Remove soft-shutdown from gatekeeper
- Add a new filter in the admin panel. It should show subtasks that are either in an active state or are in `RESULT UPLOADED` state while current time <= `TaskToCompute.deadline` + SVT. We'll leave the decision whether to wait for downloads or not up to the person shutting down the service.
- An extra, optional, feature that was not in the original issue: it might be useful to show how much time is left until all subtasks time out (in two versions: with and without the guaranteed downloads).

**Comment by rwrzesien** [comment] 2018-04-27 10:44
@cameel 

> Add a new filter in the admin panel. It should show subtasks that are either in an active state or are in RESULT UPLOADED state while current time <= TaskToCompute.deadline + SVT. We'll leave the decision whether to wait for downloads or not up to the person shutting down the service.

This can't be done until `TaskToCompute` will be stored in separate table with `deadline` as separate field.

**Comment by cameel** [comment] 2018-04-27 18:26
Then let's add `deadline` as a column on the `Subtask` table.

**Closed** 2018-05-07 12:04 UTC
Labels: admin, feature
