### ISSUE TITLE
`test_multiple_eth_accounts` from golem's concent acceptance tests is failing

### ISSUE THREAD

**Issue by dybi** [golemfactory/concent#999] opened 2018-12-05 14:36 UTC
to reproduce:
`pytest scripts/concent_acceptance_tests/force_payment/test_payment.py::RequestorDoesntPayTestCase::test_multiple_eth_accounts` on branch `chore-update-concent-acceptance-test-after-sra-update` (GM v2.17.0)

**Comment by PaweuB** [comment] 2018-12-05 15:06
Pivotal:
https://www.pivotaltracker.com/story/show/162449516

**Comment by cameel** [comment] 2018-12-07 13:01
So the problem is that Concent in UC5 allows the provider to submit acceptances for subtasks which should be paid from different Ethereum accounts belonging to the requestor while it should refuse the request? Wasn't it already fixed in #545?

**Comment by pawelkisielewicz** [comment] 2018-12-10 08:38
I asked @dybi about it, it was unclear for me as well. In this case there is one provider with two different Ethereum accounts and one requestor. According to expected message in test code Concent should answer `ServiceRefused`

**Comment by pawelkisielewicz** [comment] 2018-12-10 18:38
The problem is resolved after add commit 77c0fb41 `chore-update-concent-acceptance-test-after-sra-update`. The reason of bug was changing `provider_ethereum_public_key`'s in `task_to_compute`, where this field is made as property instead of change in `want_to_compute_task`. I added test in Concent for this case as well

**Closed by pawelkisielewicz** 2018-12-10 18:38 UTC
Labels: _high_prio, bug, payment use case
