### ISSUE TITLE
ForceGetTaskResultRejected is not stored as PendingResponse, but there is a handler for it handle_messages_from_database

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/concent#823] opened 2018-09-13 22:35 UTC
There is a flow in GetTaskResult use case when client received `ForceGetTaskResultRejected` message directly from `send` endpoint. It is the only case when this message is returned in any way. However, there is a handler for this type of `PendingResponse` object and there is a handler for it in `handle_messages_from_database` function. One of those should happen:
- `ForceGetTaskResultRejected` should be scheduled as `PendingResponse`
- `ForceGetTaskResultRejected` should be removed from `PendingResponse.ResponseType` enum and its handling from `handle_messages_from_database` function should be removed too.

@cameel Which way should it go?

**Comment by cameel** [comment] 2018-09-13 23:47
It should be removed from `receive/`. It's meant to be a synchronous response and is used only in this one case.

Looks like the confusion was caused by my mistake in the state machine blueprint (#139). I have included it on the list pending responses but it should have never been there. I'm removing it from there.

**Comment by PaweuB** [comment] 2018-09-14 12:01
Pivotal:
https://www.pivotaltracker.com/story/show/160509158

**Comment by pawelkisielewicz** [comment] 2018-09-19 11:06
It is resolved in https://github.com/golemfactory/concent/pull/835 and merged.
It is merged with renamed to correct branch name - `chore-remove-force-get-task-result-rejected-from-receive`, so it didn't close automatically.

**Closed by pawelkisielewicz** 2018-09-19 11:06 UTC
Labels: chore, result transfer use case
