### ISSUE TITLE
Replace manual ownership validation with `verify_owners()` method

### ISSUE THREAD

**Issue by dybi** [golemfactory/concent#993] opened 2018-12-03 12:15 UTC
In message handlers we manually extract and validate if particular message is signed with corresponding public key, ie:
```python
 validate_that_golem_messages_are_signed_with_key(
            requestor_public_key,
            subtask_results_rejected,
        )
        validate_that_golem_messages_are_signed_with_key(
            provider_public_key,
            subtask_results_rejected.report_computed_task,
            task_to_compute.want_to_compute_task
        )
```

whereas there is `verify_owners()` method in `golem-messages` that is specifically created for this purpose. 

Replace "our" validation with validation via `verify_owners`

**Comment by PaweuB** [comment] 2018-12-04 09:40
Pivotal:
https://www.pivotaltracker.com/story/show/162409339

**Comment by rwrzesien** [comment] 2018-12-05 13:37
Closing as a duplicate of https://github.com/golemfactory/concent/issues/563

**Closed by rwrzesien** 2018-12-05 13:37 UTC
Labels: chore
